-- MySQL Script generated by MySQL Workbench
-- Sat May 14 17:03:10 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema atl_assessment
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema atl_assessment
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `atl_assessment` DEFAULT CHARACTER SET utf8 ;
USE `atl_assessment` ;

-- -----------------------------------------------------
-- Table `atl_assessment`.`contacts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atl_assessment`.`contacts` (
  `idcontact` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcontact`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `atl_assessment`.`phone_number`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `atl_assessment`.`phone_number` (
  `idphone_number` INT NOT NULL AUTO_INCREMENT,
  `idcontact` INT NOT NULL,
  `phone_number` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idphone_number`, `idcontact`),
  INDEX `fk_phone_number_contacts_idx` (`idcontact` ASC) VISIBLE,
  CONSTRAINT `fk_phone_number_contacts`
    FOREIGN KEY (`idcontact`)
    REFERENCES `atl_assessment`.`contacts` (`idcontact`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
